"""add trainings and word_cards

Revision ID: 16a5f84d1026
Revises: 872e17bfe0f1
Create Date: 2026-03-10 22:35:46.860720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a5f84d1026'
down_revision = '872e17bfe0f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('synonyms_shown', sa.JSON(), nullable=False),
    sa.Column('synonyms_user', sa.JSON(), nullable=False),
    sa.Column('user_association', sa.JSON(), nullable=False),
    sa.Column('example_sentence', sa.String(), nullable=False),
    sa.Column('last_training_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_user_id'), 'trainings', ['user_id'], unique=False)
    op.create_index(op.f('ix_trainings_word_id'), 'trainings', ['word_id'], unique=False)
    op.create_table('word_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('associations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_cards')
    op.drop_index(op.f('ix_trainings_word_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_user_id'), table_name='trainings')
    op.drop_table('trainings')
    # ### end Alembic commands ###

