"""add is_selected_for_test to words

Revision ID: 1b7555c83d3d
Revises: 16a5f84d1026
Create Date: 2026-03-12 21:00:54.936169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7555c83d3d'
down_revision = '16a5f84d1026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('is_selected_for_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'is_selected_for_test')
    # ### end Alembic commands ###

