"""Add preferred_language to users

Revision ID: 5f8158ff3f08
Revises: 8cdb7e309a05
Create Date: 2026-01-27 15:15:30.171097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8158ff3f08'
down_revision = '8cdb7e309a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Спочатку створюємо enum тип в PostgreSQL
    language_enum = sa.Enum('ukrainian', 'english', 'russian', 'polish', 'german', 'french', 'spanish', 'italian', name='language')
    language_enum.create(op.get_bind(), checkfirst=True)
    
    # Додаємо колонку з default значенням
    op.add_column('users', sa.Column('preferred_language', language_enum, nullable=True, server_default='ukrainian'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    # Видаляємо enum тип після видалення колонки
    sa.Enum(name='language').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

