"""Add spaced repetition fields to words table

Revision ID: 6c6452ce5665
Revises: 736c478b4521
Create Date: 2026-01-26 23:12:40.711554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6452ce5665'
down_revision = '736c478b4521'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Спочатку створюємо enum тип в PostgreSQL
    study_status_enum = sa.Enum('new', 'learning', 'reviewing', 'mastered', name='studystatus')
    study_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Тепер додаємо колонки
    op.add_column('words', sa.Column('study_status', study_status_enum, nullable=True))
    op.add_column('words', sa.Column('knowledge_level', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('words', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('words', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    op.add_column('words', sa.Column('review_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('words', sa.Column('correct_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('words', sa.Column('incorrect_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('words', sa.Column('ease_factor', sa.Float(), nullable=True, server_default='2.5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'ease_factor')
    op.drop_column('words', 'incorrect_count')
    op.drop_column('words', 'correct_count')
    op.drop_column('words', 'review_count')
    op.drop_column('words', 'next_review_at')
    op.drop_column('words', 'last_reviewed_at')
    op.drop_column('words', 'knowledge_level')
    op.drop_column('words', 'study_status')
    
    # Видаляємо enum тип після видалення колонки
    op.execute('DROP TYPE IF EXISTS studystatus')
    # ### end Alembic commands ###

