"""add word card

Revision ID: 872e17bfe0f1
Revises: add_test_sessions_001
Create Date: 2026-03-10 22:03:53.527735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872e17bfe0f1'
down_revision = 'add_test_sessions_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('common_words_word_text_key', 'common_words', type_='unique')
    op.drop_index('ix_common_words_cefr_level', table_name='common_words')
    op.drop_index('ix_common_words_is_everyday_common', table_name='common_words')
    op.drop_index('ix_quests_created_at', table_name='quests')
    op.drop_index('ix_quests_is_completed', table_name='quests')
    op.drop_index('ix_quests_user_id', table_name='quests')
    op.drop_index('ix_quests_word_id', table_name='quests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_quests_word_id', 'quests', ['word_id'], unique=False)
    op.create_index('ix_quests_user_id', 'quests', ['user_id'], unique=False)
    op.create_index('ix_quests_is_completed', 'quests', ['is_completed'], unique=False)
    op.create_index('ix_quests_created_at', 'quests', ['created_at'], unique=False)
    op.create_index('ix_common_words_is_everyday_common', 'common_words', ['is_everyday_common'], unique=False)
    op.create_index('ix_common_words_cefr_level', 'common_words', ['cefr_level'], unique=False)
    op.create_unique_constraint('common_words_word_text_key', 'common_words', ['word_text'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

