"""Add sessions and session_items tables

Revision ID: 8cdb7e309a05
Revises: 6c6452ce5665
Create Date: 2026-01-27 13:54:16.108657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdb7e309a05'
down_revision = '6c6452ce5665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False, server_default='8'),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', name='sessionstatus'), nullable=False, server_default='ACTIVE'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_date'), 'sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word_id', name='uq_session_items_session_word')
    )
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_items_word_id'), 'session_items', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_items_word_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_date'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###

